apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo2
  template:
    metadata:
      labels:
        app: demo2
    spec:
      containers:
      - name: demo2
        image: rameshkumarverma/demo2:latest 
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name:demo2-service
spec:
  selector:
    app: demo2
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
